### ISSUE TITLE
Getting it to work on nixos

### ISSUE THREAD

**Issue by KarukSophia** [obfusk/jiten#115]
Hi I am having trouble getting it to work after moving to nixos. Firstly it seems that you are using `/bin/bash` instead of `/usr/bin/env bash` which works on most systems but gives issues on some, in my case nixos ([related stackoverflow question](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash)). However I was able to mitigate this with `sudo ln -s /run/current-system/sw/bin/bash /bin/bash`.

Once I got it running I ran into another issue which I don't know how to fix. Upon running `jiten -v jmdict --max 1 --word cat` I get the following error:
```
[nix-shell:~/programming/python/system-config]$ jiten -v jmdict --max 1 -
-word cat
parsing jmdict  [#################################################]  100%
Traceback (most recent call last):
  File "/nix/store/w5rhnscn5jxxy4ichr6f3gmv0mpa4x8g-python3-3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/w5rhnscn5jxxy4ichr6f3gmv0mpa4x8g-python3-3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/jiten/cli.py", line 394, in <module>
    cli(prog_name = name)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/jiten/cli.py", line 269, in jmdict
    setup_db(ctx.obj["verbose"])
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/jiten/cli.py", line 231, in setup_db
    if J.setup():
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/jiten/jmdict.py", line 406, in setup
    jmdict2sqldb(jmdict, file)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/jiten/jmdict.py", line 323, in jmdict2sqldb
    with sqlite_do(file) as c:
  File "/nix/store/w5rhnscn5jxxy4ichr6f3gmv0mpa4x8g-python3-3.7.9/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/nix/store/942v0bs0d1q0baqyyzk1d03zgdckhz8g-python3-3.7.9-env/lib/python3.7/site-packages/jiten/sql.py", line 29, in sqlite_do
    conn = sqlite3.connect(file)
sqlite3.OperationalError: unable to open database file
```
This might be because of how nixos stores programs, which is different from other distros. To clarify I am able to run jiten using `jiten` or `jiten --help`.

**Comment by obfusk** [comment]
I'm not sure how exactly you installed jiten, but the problem seems to be that it is installed in the nix store -- which is read-only -- where it can't create the .sqlite3 files.

I should look into the best way to support nixos, but for now [this nixos expression](https://gist.github.com/obfusk/c51d353e75d576bd5cb8e92456cdec47) seems to work; it's currently using the latest development version and I'm probably going to forget to update it :sweat_smile:

**Comment by KarukSophia** [comment]
Thanks works like a dream!

**Comment by obfusk** [comment]
@KarukSophia I just released `v0.4.0` and I've updated the nixos expression.

The new version has some improvements & fixes regarding romaji; feedback is always appreciated :)

**Comment by obfusk** [comment]
@KarukSophia I just released `v1.0.0` and I've updated the nix expression.

It will hopefully also be [available in NixOS](https://github.com/NixOS/nixpkgs/pull/110900) soon.

**Comment by obfusk** [comment]
@KarukSophia fyi jiten is now available in nixpkgs `master`.

**Comment by KarukSophia** [comment]
Thanks, I saw. I was following the issue on github ^.^. Do you btw have a monero adress? I'll send some your way if you want.

**Comment by obfusk** [comment]
I don't. But thank you for the offer.
