### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by KarukSophia** [obfusk/jiten#87]
Hi, I tried installing the program, but it gives me an error:
Input:
`$ pip install jiten`
Output:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting jiten
  Using cached jiten-0.3.3.tar.gz (63.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d8s9fd2s/jiten/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d8s9fd2s/jiten/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d9fo6ykz
         cwd: /tmp/pip-install-d8s9fd2s/jiten/
    Complete output (8 lines):
    make: *** No rule to make target 'patch'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d8s9fd2s/jiten/setup.py", line 21, in <module>
        subprocess.run("make patch", shell = True, check = True)
      File "/usr/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command 'make patch' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
OS is linux, distribution is Artix.

**Comment by obfusk** [comment]
Oops. Thanks for reporting that! Should be fixed now.

**Comment by obfusk** [comment]
@KarukSophia please feel free to report any other issues you may encounter.
You can also email jiten@obfusk.dev if you have any questions or feedback :)
